name: humanbenchmark
description: "An app to test your abilities."
publish_to: 'none'

version: 1.0.9+19

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2
  provider: ^6.1.0
  share_plus: ^10.0.2
  just_audio: ^0.9.37
  flutter_tts: ^3.2.2
  path_provider: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/sentences.json
    - assets/articles.json
    - assets/words.json
    - assets/human-benchmark.webp
    - assets/human-benchmark-no-background.webp
    - assets/target.webp
    - assets/frequencies/250.mp3
    - assets/frequencies/500.mp3
    - assets/frequencies/1000.mp3
    - assets/frequencies/2000.mp3
    - assets/frequencies/4000.mp3
    - assets/frequencies/8000.mp3
    - assets/frequencies/10000.mp3
    - assets/frequencies/12000.mp3
    - assets/frequencies/14000.mp3
    - assets/frequencies/16000.mp3
    - assets/frequencies/18000.wav
    - assets/frequencies/20000.wav
    - assets/frequencies/22000.wav
    - assets/iq/answers.json
    - assets/iq/1/test1.webp
    - assets/iq/1/1-1.webp
    - assets/iq/1/1-2.webp
    - assets/iq/1/1-3.webp
    - assets/iq/1/1-4.webp
    - assets/iq/1/1-5.webp
    - assets/iq/1/1-6.webp
    - assets/iq/2/test2.webp
    - assets/iq/2/2-1.webp
    - assets/iq/2/2-2.webp
    - assets/iq/2/2-3.webp
    - assets/iq/2/2-4.webp
    - assets/iq/2/2-5.webp
    - assets/iq/2/2-6.webp
    - assets/iq/3/test3.webp
    - assets/iq/3/3-1.webp
    - assets/iq/3/3-2.webp
    - assets/iq/3/3-3.webp
    - assets/iq/3/3-4.webp
    - assets/iq/3/3-5.webp
    - assets/iq/4/test4.webp
    - assets/iq/4/4-1.webp
    - assets/iq/4/4-2.webp
    - assets/iq/4/4-3.webp
    - assets/iq/4/4-4.webp
    - assets/iq/4/4-5.webp
    - assets/iq/4/4-6.webp
    - assets/iq/5/test5.webp
    - assets/iq/5/5-1.webp
    - assets/iq/5/5-2.webp
    - assets/iq/5/5-3.webp
    - assets/iq/5/5-4.webp
    - assets/iq/5/5-5.webp
    - assets/iq/6/test6.webp
    - assets/iq/6/6-1.webp
    - assets/iq/6/6-2.webp
    - assets/iq/6/6-3.webp
    - assets/iq/6/6-4.webp
    - assets/iq/6/6-5.webp
    - assets/iq/6/6-6.webp
    - assets/iq/7/test7.webp
    - assets/iq/7/7-1.webp
    - assets/iq/7/7-2.webp
    - assets/iq/7/7-3.webp
    - assets/iq/7/7-4.webp
    - assets/iq/7/7-5.webp
    - assets/iq/8/test8.webp
    - assets/iq/8/8-1.webp
    - assets/iq/8/8-2.webp
    - assets/iq/8/8-3.webp
    - assets/iq/8/8-4.webp
    - assets/iq/8/8-5.webp
    - assets/iq/9/test9.webp
    - assets/iq/9/9-1.webp
    - assets/iq/9/9-2.webp
    - assets/iq/9/9-3.webp
    - assets/iq/9/9-4.webp
    - assets/iq/9/9-5.webp
    - assets/iq/10/test10.webp
    - assets/iq/10/10-1.webp
    - assets/iq/10/10-2.webp
    - assets/iq/10/10-3.webp
    - assets/iq/10/10-4.webp
    - assets/iq/11/test11.webp
    - assets/iq/11/11-1.webp
    - assets/iq/11/11-2.webp
    - assets/iq/11/11-3.webp
    - assets/iq/11/11-4.webp
    - assets/iq/11/11-5.webp
    - assets/iq/12/test12.webp
    - assets/iq/12/12-1.webp
    - assets/iq/12/12-2.webp
    - assets/iq/12/12-3.webp
    - assets/iq/12/12-4.webp
    - assets/iq/13/test13.webp
    - assets/iq/13/13-1.webp
    - assets/iq/13/13-2.webp
    - assets/iq/13/13-3.webp
    - assets/iq/13/13-4.webp
    - assets/iq/14/test14.webp
    - assets/iq/14/14-1.webp
    - assets/iq/14/14-2.webp
    - assets/iq/14/14-3.webp
    - assets/iq/14/14-4.webp
    - assets/iq/14/14-5.webp
    - assets/iq/15/test15.webp
    - assets/iq/15/15-1.webp
    - assets/iq/15/15-2.webp
    - assets/iq/15/15-3.webp
    - assets/iq/15/15-4.webp
    - assets/iq/15/15-5.webp
    - assets/iq/15/15-6.webp
    - assets/iq/16/test16.webp
    - assets/iq/16/16-1.webp
    - assets/iq/16/16-2.webp
    - assets/iq/16/16-3.webp
    - assets/iq/16/16-4.webp
    - assets/iq/16/16-5.webp
    - assets/iq/17/test17.webp
    - assets/iq/17/17-1.webp
    - assets/iq/17/17-2.webp
    - assets/iq/17/17-3.webp
    - assets/iq/17/17-4.webp
    - assets/iq/17/17-5.webp
    - assets/iq/17/17-6.webp
    - assets/iq/18/test18.webp
    - assets/iq/18/18-1.webp
    - assets/iq/18/18-2.webp
    - assets/iq/18/18-3.webp
    - assets/iq/18/18-4.webp
    - assets/iq/18/18-5.webp
    - assets/iq/18/18-6.webp
    - assets/iq/19/test19.webp
    - assets/iq/19/19-1.webp
    - assets/iq/19/19-2.webp
    - assets/iq/19/19-3.webp
    - assets/iq/19/19-4.webp
    - assets/iq/19/19-5.webp
    - assets/iq/19/19-6.webp
    - assets/iq/20/test20.webp
    - assets/iq/20/20-1.webp
    - assets/iq/20/20-2.webp
    - assets/iq/20/20-3.webp
    - assets/iq/20/20-4.webp
    - assets/iq/20/20-5.webp
    - assets/iq/20/20-6.webp
    - assets/iq/21/test21.webp
    - assets/iq/21/21-1.webp
    - assets/iq/21/21-2.webp
    - assets/iq/21/21-3.webp
    - assets/iq/21/21-4.webp
    - assets/iq/21/21-5.webp
    - assets/iq/22/test22.webp
    - assets/iq/22/22-1.webp
    - assets/iq/22/22-2.webp
    - assets/iq/22/22-3.webp
    - assets/iq/22/22-4.webp
    - assets/iq/23/test23.webp
    - assets/iq/23/23-1.webp
    - assets/iq/23/23-2.webp
    - assets/iq/23/23-3.webp
    - assets/iq/23/23-4.webp
    - assets/iq/23/23-5.webp
    - assets/iq/23/23-6.webp
    - assets/iq/24/test24.webp
    - assets/iq/24/24-1.webp
    - assets/iq/24/24-2.webp
    - assets/iq/24/24-3.webp
    - assets/iq/24/24-4.webp
    - assets/iq/24/24-5.webp
    - assets/iq/24/24-6.webp
    - assets/iq/25/test25.webp
    - assets/iq/25/25-1.webp
    - assets/iq/25/25-2.webp
    - assets/iq/25/25-3.webp
    - assets/iq/25/25-4.webp
    - assets/iq/25/25-5.webp
    - assets/iq/25/25-6.webp
    - assets/iq/26/test26.webp
    - assets/iq/26/26-1.webp
    - assets/iq/26/26-2.webp
    - assets/iq/26/26-3.webp
    - assets/iq/26/26-4.webp
    - assets/iq/26/26-5.webp
    - assets/iq/26/26-6.webp
    - assets/iq/27/test27.webp
    - assets/iq/27/27-1.webp
    - assets/iq/27/27-2.webp
    - assets/iq/27/27-3.webp
    - assets/iq/27/27-4.webp
    - assets/iq/27/27-5.webp
    - assets/iq/27/27-6.webp
    - assets/iq/28/test28.webp
    - assets/iq/28/28-1.webp
    - assets/iq/28/28-2.webp
    - assets/iq/28/28-3.webp
    - assets/iq/28/28-4.webp
    - assets/iq/28/28-5.webp
    - assets/iq/28/28-6.webp
    - assets/iq/29/test29.webp
    - assets/iq/29/29-1.webp
    - assets/iq/29/29-2.webp
    - assets/iq/29/29-3.webp
    - assets/iq/29/29-4.webp
    - assets/iq/29/29-5.webp
    - assets/iq/29/29-6.webp
    - assets/iq/30/test30.webp
    - assets/iq/30/30-1.webp
    - assets/iq/30/30-2.webp
    - assets/iq/30/30-3.webp
    - assets/iq/30/30-4.webp
    - assets/iq/30/30-5.webp

flutter_icons:
  android: true
  ios: true
  image_path: "assets/human-benchmark.webp"